# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-18.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      
      - name: Packing_wine
        run: |
						dpkg –add-architecture i386
						wget -nc https://dl.winehq.org/wine-builds/winehq.key
						sudo mv winehq.key /usr/share/keyrings/winehq-archive.key
						wget -nc https://dl.winehq.org/wine-builds/ubuntu/dists/bionic/winehq-bionic.sources
						sudo mv winehq-bionic.sources /etc/apt/sources.list.d/
						apt update
						sudo apt-get clean
						sudo apt-get --download-only install winehq-stable
						apt download fontconfig-config
						find ./debs -exec dpkg -x {} ./ \;
						ls -a
